name: Pact-JVM Build

on:
  push:
    branches:
      - master
      - v4.2.x
  pull_request:
    branches: [ master, v4.1.x, v4.2.x, v5.0.x ]

jobs:
  latest_jdk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        module: [ core, 'consumer -x :consumer:junit:clojureTest', provider, pact-specification-test ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - run: ./gradlew -v
    - name: Build with Gradle
      run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} build

  supported_jdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ core, consumer, provider, pact-specification-test ]
        jdk: [ 11, 12, 13, 14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - run: ./gradlew -v
      - run: env
      - name: Build with Gradle
        run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} build
